# Generated by Django 3.2.8 on 2021-10-11 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobber', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='recruiter_contacts',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='recruiter_contacts',
            field=models.ManyToManyField(related_name='recruiter_contacts', to='jobber.Contact'),
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='referral_contacts',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='referral_contacts',
            field=models.ManyToManyField(related_name='referral_contacts', to='jobber.Contact'),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ManyToManyField(to='jobber.Author'),
        ),
    ]
