# Generated by Django 3.2.8 on 2021-10-24 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobber', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='recruiter_contacts',
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_type',
            field=models.CharField(choices=[('REF', 'Reference'), ('REC', 'Recruiter')], default='REF', max_length=9),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='recruiter_contact',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_contact', to='jobber.contact'),
            preserve_default=False,
        ),
    ]
