# Generated by Django 3.2.8 on 2021-10-12 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobber', '0002_auto_20211011_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='application',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='application',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='events',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='recruiter_contacts',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='referral_contacts',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='stage',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='CoverLetter',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Opportunity',
        ),
        migrations.DeleteModel(
            name='Resume',
        ),
        migrations.DeleteModel(
            name='Stage',
        ),
    ]
