# Generated by Django 3.2.8 on 2021-10-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobber', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='interview_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
