# Generated by Django 3.2.8 on 2021-10-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobber', '0005_alter_opportunity_interview_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='interview_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
