# Generated by Django 3.2.8 on 2021-11-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobber', '0005_auto_20211104_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=12),
        ),
    ]
