# Generated by Django 3.2.8 on 2021-11-09 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobber', '0006_alter_contact_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='interview_date',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='interview_location',
        ),
    ]
