# Generated by Django 3.2.8 on 2021-10-13 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobber', '0006_alter_opportunity_interview_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='cover_letter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobber.coverletter'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobber.author'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobber.application'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='events',
            field=models.ManyToManyField(blank=True, null=True, to='jobber.Event'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='recruiter_contacts',
            field=models.ManyToManyField(blank=True, null=True, related_name='recruiter_contacts', to='jobber.Contact'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='referral_contacts',
            field=models.ManyToManyField(blank=True, null=True, related_name='referral_contacts', to='jobber.Contact'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='resume',
            name='experiences',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.TextField(),
        ),
    ]
