# Generated by Django 3.2.8 on 2021-10-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobber', '0007_auto_20211013_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='subtitle',
            field=models.CharField(max_length=400),
        ),
    ]
