# Generated by Django 3.2.8 on 2021-11-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobber', '0008_auto_20211109_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
