# Generated by Django 3.2.8 on 2021-11-12 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobber', '0010_auto_20211110_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobber.application'),
        ),
    ]
