# Generated by Django 3.2.8 on 2021-11-10 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_remove_profile_name'),
        ('jobber', '0010_auto_20211110_0712'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('COMPLETE', 'Complete'), ('CLOSED', 'Closed')], default='OPEN', max_length=9)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobber.application')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now_add=True)),
                ('votes', models.IntegerField(default=0)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.feedback')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
